### ISSUE TITLE
Escape principal Id characters

### ISSUE THREAD

**Issue by diablouma** [littlehorse-enterprises/littlehorse#456]

**Comment by coltmcnealy-lh** [comment]
Unfortunately, we do need to escape the `Principal` ID characters. In the rest of LittleHorse we use `kebab-case` for any `Getable` ID's in order to work well with our RocksDB key schemas; however, here we can't expect our users to fully control the Principal ID's since they can come from OAuth Client ID's.

I think maybe URL encoding is a good proposal to look into. What do you think @eduwercamacaro @sauljabin ?

**Comment by sauljabin** [comment]
I need more context, where is the description?

**Comment by coltmcnealy-lh** [comment]
Completed by #749
