### ISSUE TITLE
Naming for user task node

### ISSUE THREAD

**Issue by eduwercamacaro** [littlehorse-enterprises/littlehorse#779]
https://github.com/littlehorse-enterprises/littlehorse/blob/master/schemas/wf_spec.proto#L192

**Comment by coltmcnealy-lh** [comment]
In case the protobuf changes from another PR, the issue is that we use a `string` and not a `UserTaskDefId`. This must be resolved before 1.0.0

```
message UserTaskNode {
  string user_task_def_name = 1;

```

**Comment by coltmcnealy-lh** [comment]
Now I remember why I did it this way. Not fully proud of it, but the reasons are somewhat sound (once you ignore the fact that I violated a "best practice" by directly exposing the internal storage model protos as our API).

The reason for this is that the `UserTaskNode` is shared between the `PutWfSpecRequest` and the `WfSpec`.

In the `PutWfSpecRequest` we do not specify the `user_task_def_version`; but we then _infer_ the version by choosing the latest available `UserTaskDef` for the specified name.

The `WfSpec#validate()` method ends up populating the `user_task_def_version` field inside the `UserTaskNode` so that it will actually always be set (not optional) when a `WfRun` looks up the `WfSpec`.

No change needed.
